"""corrigindo mapped column de quantidade para int

Revision ID: 6ac17e4b9cdf
Revises: 7e6492fec059
Create Date: 2026-08-15 22:24:24.918782

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ac17e4b9cdf"
down_revision: Union[str, Sequence[str], None] = "7e6492fec059"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ItensPedidos", schema=None) as batch_op:
        batch_op.alter_column(
            "quantidade",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ItensPedidos", schema=None) as batch_op:
        batch_op.alter_column(
            "quantidade",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
