"""nome como campo unique e obrigatório

Revision ID: 7e6492fec059
Revises: f1a58fff2ee1
Create Date: 2026-07-05 20:36:20.701615

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7e6492fec059"
down_revision: Union[str, Sequence[str], None] = "f1a58fff2ee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Usuarios", schema=None) as batch_op:
        batch_op.create_unique_constraint("uk_nome", ["nome"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Usuarios", schema=None) as batch_op:
        batch_op.drop_constraint("uk_nome", type_="unique")

    # ### end Alembic commands ###
