"""postgres migration

Revision ID: ade3a278e602
Revises:
Create Date: 2026-08-20 16:51:55.021687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ade3a278e602"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Usuarios",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("senha", sa.String(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "Pedidos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("usuario", sa.Integer(), nullable=False),
        sa.Column("preco", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario"],
            ["Usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ItensPedidos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("sabor", sa.String(), nullable=False),
        sa.Column("tamanho", sa.String(), nullable=False),
        sa.Column("preco_unitario", sa.Float(), nullable=False),
        sa.Column("pedido", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pedido"],
            ["Pedidos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ItensPedidos")
    op.drop_table("Pedidos")
    op.drop_table("Usuarios")
    # ### end Alembic commands ###
