"""Corrigindo relação entre models

Revision ID: c0cb65629a6b
Revises: b6a6a38fb22d
Create Date: 2026-06-26 19:45:05.040659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0cb65629a6b'
down_revision: Union[str, Sequence[str], None] = 'b6a6a38fb22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItensPedidos', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_pedido_itens_id', 'Pedidos', ['pedido'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ItensPedidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedido_itens_id', type_='foreignkey')

    # ### end Alembic commands ###
