"""Email como unique

Revision ID: f1a58fff2ee1
Revises: c0cb65629a6b
Create Date: 2026-06-26 19:49:26.964555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a58fff2ee1'
down_revision: Union[str, Sequence[str], None] = 'c0cb65629a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint('uk_usuario_email', ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Usuarios', schema=None) as batch_op:
        batch_op.drop_constraint('uk_usuario_email', type_='unique')

    # ### end Alembic commands ###
